# -*- coding: utf-8 -*-
"""healthcare_capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLOXly1iZk-9lk4-PE4AkVjnMzaRCmyi
"""

# 🏥 Healthcare Capstone: Breast Cancer Tumor Classification

## Project Components
| Requirement        | Implementation                              |
|--------------------|---------------------------------------------|
| Data Processing    | Cells 1-5: Cleansing + 3 Visualizations     |
| Machine Learning   | Cells 6-8: Random Forest Classifier         |
| Generative AI      | Cell 9: Gemini API — Clinical Summary Gen.  |

Dataset: Wisconsin Breast Cancer Dataset (sklearn built-in)
Goal: Classify tumors as malignant/benign + communicate results via AI

!pip install -q google-genai

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_breast_cancer

# Load dataset
cancer = load_breast_cancer()
df = pd.DataFrame(cancer.data, columns=cancer.feature_names)
df['diagnosis'] = pd.Categorical.from_codes(cancer.target, ['malignant', 'benign'])

print("Dataset Shape:", df.shape)
print("\nDiagnosis Counts:")
print(df['diagnosis'].value_counts())
df.head()

print("=== Missing Values ===")
print(df.isnull().sum().sum(), "missing values found")

print("\n=== Basic Statistics ===")
df.describe().round(2)

plt.figure(figsize=(6, 4))
colors = ['#e74c3c', '#2ecc71']
df['diagnosis'].value_counts().plot(kind='bar', color=colors, edgecolor='black')
plt.title('Breast Cancer Diagnosis Distribution', fontsize=14)
plt.xlabel('Diagnosis')
plt.ylabel('Number of Patients')
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig('diagnosis_distribution.png')
plt.show()
print("Chart saved!")

# Compare top 4 features between malignant and benign
features_to_plot = ['mean radius', 'mean texture', 'mean perimeter', 'mean area']

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
axes = axes.flatten()

for i, feature in enumerate(features_to_plot):
    for diagnosis, color in zip(['malignant', 'benign'], ['#e74c3c', '#2ecc71']):
        subset = df[df['diagnosis'] == diagnosis][feature]
        axes[i].hist(subset, alpha=0.6, label=diagnosis, color=color, bins=20)
    axes[i].set_title(f'{feature.title()}')
    axes[i].legend()
    axes[i].set_xlabel('Value')
    axes[i].set_ylabel('Count')

plt.suptitle('Feature Distribution: Malignant vs Benign', fontsize=14)
plt.tight_layout()
plt.savefig('feature_comparison.png')
plt.show()
print("Chart saved!")

plt.figure(figsize=(10, 8))
# Use only first 10 features to keep it readable
top_features = df.columns[:10].tolist()
corr = df[top_features].corr()
sns.heatmap(corr, annot=True, fmt='.2f', cmap='RdYlGn', linewidths=0.5)
plt.title('Feature Correlation Heatmap (Top 10 Features)', fontsize=13)
plt.tight_layout()
plt.savefig('correlation_heatmap.png')
plt.show()
print("Chart saved!")

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, classification_report,
                              ConfusionMatrixDisplay)
from sklearn.preprocessing import LabelEncoder

# Prepare data
X = df.drop('diagnosis', axis=1)
le = LabelEncoder()
y = le.fit_transform(df['diagnosis'])  # malignant=0, benign=1

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print(f"✅ Model Accuracy: {acc:.2%}")
print("\n📋 Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Malignant', 'Benign']))

fig, ax = plt.subplots(figsize=(6, 5))
ConfusionMatrixDisplay.from_estimator(
    model, X_test, y_test,
    display_labels=['Malignant', 'Benign'],
    cmap='Blues', ax=ax
)
ax.set_title('Confusion Matrix: Tumor Classification', fontsize=13)
plt.tight_layout()
plt.savefig('confusion_matrix.png')
plt.show()
print("Chart saved!")

importances = pd.Series(
    model.feature_importances_,
    index=cancer.feature_names
).sort_values(ascending=True).tail(10)  # Top 10 features

plt.figure(figsize=(8, 6))
importances.plot(kind='barh', color='steelblue', edgecolor='black')
plt.title('Top 10 Most Important Features for Diagnosis', fontsize=13)
plt.xlabel('Importance Score')
plt.tight_layout()
plt.savefig('feature_importance.png')
plt.show()
print("Chart saved!")

from google import genai
from google.colab import userdata

try:
    api_key = userdata.get('GOOGLE_API_KEY')
    client = genai.Client(api_key=api_key)

    report = classification_report(
        y_test, y_pred,
        target_names=['Malignant', 'Benign']
    )

    prompt = f"""
    You are a Senior Medical Research Data Analyst.

    A machine learning model was trained on the Wisconsin Breast Cancer Dataset
    to classify tumors as malignant (cancerous) or benign (non-cancerous)
    based on cell nucleus measurements.

    Model Results:
    - Model Used: Random Forest Classifier
    - Accuracy: {acc:.2%}
    - Classification Report:
    {report}

    The most important features were: mean radius, mean perimeter,
    mean concave points, and mean area.

    Please provide:
    1. A brief explanation of what this model does and why it matters in healthcare.
    2. A simple explanation of the accuracy and what the classification report means
       for malignant vs benign detection.
    3. What the most important features tell us medically about tumor detection.
    4. A disclaimer that this is an AI-assisted screening tool and all results
       must be reviewed and confirmed by a qualified medical professional.
    """

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    print("=" * 60)
    print("🤖 AI-Generated Healthcare Summary")
    print("=" * 60)
    print(response.text)

    # Save to file
    with open("ai_summary.txt", "w") as f:
        f.write(response.text)
    print("\n✅ Summary saved to ai_summary.txt")

except Exception as e:
    print(f"❌ Error: {e}")

from google.colab import files

# Download all saved files
files_to_download = [
    'diagnosis_distribution.png',
    'feature_comparison.png',
    'correlation_heatmap.png',
    'confusion_matrix.png',
    'feature_importance.png',
    'ai_summary.txt'
]

for file in files_to_download:
    files.download(file)

print("✅ All files downloaded!")